version: '3.4'
services:

  #PHP Service
  app:
    image: docker-laravel
    container_name: laravel-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # The Database
  database:
    image: mysql:5.7
    container_name: laravel-db
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    ports:
        - "33061:3306"

volumes:
  dbdata:
